export const matchesData = [
  {
    id: 1,
    team1: 'RCB',
    team2: 'Chennai',
    time: '9.00 PM',
    team1FullName: 'Royalle Challengers Bangalore',
    team2FullName: 'Chennai Super Kings',
    maxPrice: '₹ 10,000',
  },
  {
    id: 2,
    team1: 'MI',
    team2: 'Chennai',
    time: '7.00 PM',
    team1FullName: 'Mumbai Indians',
    team2FullName: 'Chennai Super Kings',
    maxPrice: '₹ 8,000',
  },
  {
    id: 3,
    team1: 'RR',
    team2: 'DC',
    time: '8.00 PM',
    team1FullName: 'Rajasthan Royals',
    team2FullName: 'Delhi Capitals',
    maxPrice: '₹ 100,000',
  },
  {
    id: 4,
    team1: 'SRH',
    team2: 'KKR',
    time: '7.00 PM',
    team1FullName: 'Sunrisers Hyderabad',
    team2FullName: 'Kolkata Knight Riders',
    maxPrice: '₹ 10,000',
  },
  {
    id: 5,
    team1: 'RCB',
    team2: 'Chennai',
    time: '9.00 PM',
    team1FullName: 'Royalle Challengers Bangalore',
    team2FullName: 'Chennai Super Kings',
    maxPrice: '₹ 10,000',
  },
];
