export const matchesData = [
  {
    id: 1,
    team1: "RCB",
    team2: "Chennai",
    time: "9.00 PM",
    team1FullName: "Royalle Challengers Bangalore",
    team2FullName: "Chennai Super Kings",
    maxPrice: "₹ 10,000",
    progressWidth: "50%",
    totalSpot: 200,
  },
  {
    id: 2,
    team1: "MI",
    team2: "Chennai",
    time: "7.00 PM",
    team1FullName: "Mumbai Indians",
    team2FullName: "Chennai Super Kings",
    maxPrice: "₹ 8,000",
    progressWidth: "40%",
    totalSpot: 200,
  },
  {
    id: 3,
    team1: "RR",
    team2: "DC",
    time: "8.00 PM",
    team1FullName: "Rajasthan Royals",
    team2FullName: "Delhi Capitals",
    maxPrice: "₹ 100,000",
    progressWidth: "50%",
    totalSpot: 200,
  },
  {
    id: 4,
    team1: "SRH",
    team2: "KKR",
    time: "7.00 PM",
    team1FullName: "Sunrisers Hyderabad",
    team2FullName: "Kolkata Knight Riders",
    maxPrice: "₹ 10,000",
    progressWidth: "30%",
    totalSpot: 200,
  },
  {
    id: 5,
    team1: "RCB",
    team2: "Chennai",
    time: "9.00 PM",
    team1FullName: "Royalle Challengers Bangalore",
    team2FullName: "Chennai Super Kings",
    maxPrice: "₹ 10,000",
    progressWidth: "20%",
    totalSpot: 200,
  },
];

export const play11Data = {
  team1: {
    name: "RCB",
    batsman: [
      {
        name: "Virat Kohli",

        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },

      {
        name: "Devdutt Padikkal",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },

      {
        name: "Kyle Jamieson",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
    allRounder: [
      {
        name: "Washington Sundar",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Glenn Maxwell",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
    bowler: [
      {
        name: "Yuzvendra Chahal",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
      {
        name: "Mohammed Siraj",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
      {
        name: "Harshal Patel",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
      {
        name: "Hazlewood",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
    ],
    wicketKeeper: [
      {
        name: "AB de Villiers",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Rajat Patidar",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
  },
  team2: {
    name: "CSK",
    batsman: [
      {
        name: "Faf du Plessis",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Ruturaj Gaikwad",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Suresh Raina",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },

      {
        name: "Moeen Ali",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
    allRounder: [
      {
        name: "Ravindra Jadeja",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Sam Curran",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
    bowler: [
      {
        name: "Deepak Chahar",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
      {
        name: "Shardul Thakur",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
      {
        name: "Imran Tahir",
        runs: 0,
        balls: 0,
        wickets: 0,
        economy: 0,
      },
    ],
    wicketKeeper: [
      {
        name: "MS Dhoni",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
      {
        name: "Robin Uthappa",
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
      },
    ],
  },
};
